version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no",
      "--maxmemory", "128mb",
      "--maxmemory-policy", "allkeys-lru",
      "--hz", "10",
      "--protected-mode", "no",
      "--tcp-backlog", "512",
      "--tcp-keepalive", "60",
      "--io-threads", "2"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100M"
    networks:
      - rinhattus-net

  api1:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api1
    depends_on:
      - redis
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "90M"
    networks:
      - rinhattus-net

  api2:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api2
    depends_on:
      - redis
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "90M"
    networks:
      - rinhattus-net

  nginx:
    image: nginx:1.27-alpine
    container_name: rinhattus-nginx
    ports:
      - "9001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"
    networks:
      - rinhattus-net

networks:
  rinhattus-net:
    driver: bridge
