version: "3.9"

services:
  api1:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api1
    environment:
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx128m -Dreactor.netty.pool.leasingStrategy=lifo
    deploy:
      resources:
        limits:
          cpus: "0.675"
          memory: "154MB"
    networks:
      - rinhattus-net

  api2:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api2
    environment:
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx128m -Dreactor.netty.pool.leasingStrategy=lifo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
    networks:
      - rinhattus-net

  nginx:
    image: nginx:1.27-alpine
    container_name: rinhattus-nginx
    ports:
      - "9001:9001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    networks:
      - rinhattus-net

networks:
  rinhattus-net:
    driver: bridge
