version: "3.9"

services:
  api1:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api1
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140M"
    networks:
      - rinhattus-net

  api2:
    image: jmz25/rinhattus-api:latest
    container_name: rinhattus-api2
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140M"
    networks:
      - rinhattus-net

  nginx:
    image: nginx:1.27-alpine
    container_name: rinhattus-nginx
    ports:
      - "9001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70M"
    networks:
      - rinhattus-net

networks:
  rinhattus-net:
    driver: bridge
