version: "3.9"

services:
  api1:
    build: .
    container_name: rinhattus-api1
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "165MB"
    environment:
      - JAVA_OPTS=-server -XX:+UseG1GC -XX:MaxGCPauseMillis=1 -XX:+TieredCompilation -XX:TieredStopAtLevel=4 -XX:CompileThreshold=100
      - MALLOC_ARENA_MAX=2
    networks:
      - rinhattus-net
    sysctls:
      - net.core.somaxconn=4096
      - net.ipv4.tcp_tw_reuse=1
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  api2:
    build: .
    container_name: rinhattus-api2
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "165MB"
    networks:
      - rinhattus-net
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_tw_reuse=1
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  nginx:
    image: nginx:1.27-alpine
    container_name: rinhattus-nginx
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    networks:
      - rinhattus-net
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_tw_reuse=1

networks:
  rinhattus-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: rinhattus0
      com.docker.network.driver.mtu: 1500
