version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no",
      "--maxmemory", "128mb",
      "--maxmemory-policy", "allkeys-lru",
      "--hz", "10",
      "--protected-mode", "no",
      "--tcp-backlog", "512",
      "--tcp-keepalive", "60",
      "--io-threads", "2"
    ]
    ports:
      - "6379:6379"
    networks:
      - rinhattus-net

  api1:
    image: eclipse-temurin:21-jre-jammy
    container_name: rinha-api1-dev
    volumes:
      - ./target/rinha-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-Xms64m", "-Xmx96m", "-XX:+UseSerialGC", "-jar", "app.jar", "--server.port=8080"]
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 100M
    networks:
      - rinhattus-net

  api2:
    image: eclipse-temurin:21-jre-jammy
    container_name: rinha-api2-dev
    volumes:
      - ./target/rinha-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-Xms64m", "-Xmx96m", "-XX:+UseSerialGC", "-jar", "app.jar", "--server.port=8081"]
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 100M
    networks:
      - rinhattus-net

  nginx:
    image: nginx:1.27-alpine
    container_name: rinhattus-nginx-dev
    ports:
      - "9001:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinhattus-net

networks:
  rinhattus-net:
    driver: bridge
