spring:
  main:
    banner-mode: "off"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 1MB

server:
  port: 8080
  http2:
    enabled: true

logging:
  level:
    root: WARN
