server:
  port: 8080
  shutdown: immediate
  netty:
    connection-timeout: 1000ms
    idle-timeout: 5s
  max-http-header-size: 8KB
  compression:
    enabled: false

spring:
  application:
    name: rinha
#  threads:
#    virtual:
#        enabled: true

  main:
    banner-mode: "off"
    lazy-initialization: true
    web-application-type: reactive
    register-shutdown-hook: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: false
      WRITE_NULL_MAP_VALUES: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      USE_ANNOTATIONS: false
    generator:
      WRITE_NUMBERS_AS_STRINGS: false

reactor:
  netty:
    pool:
      max-connections: 2000
      pending-acquire-max-count: 4000
      leasing-strategy: lifo
      max-idle-time: 10s
      acquire-timeout: 2s
      max-life-time: 60s
    worker-count: 4
    shutdown-quiet-period: 0
    shutdown-timeout: 0
    ioWorkerCount: 2
    ioSelectCount: 1

#logging:
#  level:
#    root: ERROR
#    org.springframework: ERROR
#    reactor.netty: ERROR
#    io.netty: ERROR
#    org.apache.catalina: ERROR
#    org.hibernate: ERROR
#    org.springframework.web: ERROR

management:
  endpoints:
    enabled-by-default: false
spring.webflux:
  max-in-memory-size: 1MB
  static-path-pattern: /static/**