server:
  port: 8080
  shutdown: immediate
  compression:
    enabled: false
  max-http-header-size: 8KB

spring:
  application:
    name: rinha

  main:
    banner-mode: "off"
    lazy-initialization: false
    register-shutdown-hook: false
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
      - org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: false
      WRITE_NULL_MAP_VALUES: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      USE_ANNOTATIONS: false
    generator:
      WRITE_NUMBERS_AS_STRINGS: false

management:
  endpoints:
    enabled-by-default: false
